"""Add thumbnail to Recipe

Revision ID: e995b7308d21
Revises: abb754e0190e
Create Date: 2025-08-22 13:24:39.810531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e995b7308d21'
down_revision: Union[str, Sequence[str], None] = 'abb754e0190e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('thumbnail', sa.String(), nullable=True))
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=True)
    op.drop_column('recipes', 'thumbnail')
    # ### end Alembic commands ###
